# Copyright 2016, 2017 Peter Dimov
# Copyright 2021 Matt Borland
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

dist: focal 

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=special_fun
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=distribution_tests
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=quadrature
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=float128_tests
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=../example//examples
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=../tools
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: ppc64le
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=misc
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=special_fun
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=distribution_tests
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=quadrature
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=float128_tests
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=../example//examples
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=../tools
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: arm64
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=misc
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=special_fun
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=distribution_tests
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=quadrature
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=float128_tests
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=../example//examples
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=../tools
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      arch: s390x
      compiler: g++
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++11,14,17,2a TEST_SUITE=misc
      addons:
        apt:
          packages:
            - g++
            - libgmp-dev
            - libmpfr-dev
            - libfftw3-dev
          sources:
            - ubuntu-toolchain-r-test

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init libs/config
  - git submodule update --init libs/format
  - git submodule update --init libs/numeric
  - git submodule update --init libs/type_traits
  - git submodule update --init libs/timer
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/math
  - python tools/boostdep/depinst/depinst.py math
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - (cd libs/config/test && ../../../b2 config_info_travis_install toolset=$TOOLSET && ./config_info_travis)
  - (cd libs/math/test && travis_wait 60 ../../../b2 -j3 toolset=$TOOLSET $TEST_SUITE define=CI_SUPPRESS_KNOWN_ISSUES define=SLOW_COMPILER)

notifications:
  email:
    on_success: always
