//  Copyright (c) 2020 John Maddock
//  Use, modification and distribution are subject to the
//  Boost Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef BOOST_MATH_TOOLS_CXX03_WARN_HPP
#define BOOST_MATH_TOOLS_CXX03_WARN_HPP

#include <boost/math/tools/config.hpp>

#if defined(BOOST_NO_CXX11_NOEXCEPT)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_NOEXCEPT"
#endif
#if defined(BOOST_NO_CXX11_NOEXCEPT) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_NOEXCEPT"
#endif
#if defined(BOOST_NO_CXX11_NOEXCEPT) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_NOEXCEPT"
#endif
#if defined(BOOST_NO_CXX11_RVALUE_REFERENCES) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_RVALUE_REFERENCES"
#endif
#if defined(BOOST_NO_SFINAE_EXPR) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_SFINAE_EXPR"
#endif
#if defined(BOOST_NO_CXX11_AUTO_DECLARATIONS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_AUTO_DECLARATIONS"
#endif
#if defined(BOOST_NO_CXX11_LAMBDAS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_LAMBDAS"
#endif
#if defined(BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX"
#endif
#if defined(BOOST_NO_CXX11_HDR_TUPLE) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_HDR_TUPLE"
#endif
#if defined(BOOST_NO_CXX11_HDR_INITIALIZER_LIST) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_HDR_INITIALIZER_LIST"
#endif
#if defined(BOOST_NO_CXX11_HDR_CHRONO) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_HDR_CHRONO"
#endif
#if defined(BOOST_NO_CXX11_CONSTEXPR) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_CONSTEXPR"
#endif
#if defined(BOOST_NO_CXX11_NULLPTR) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_NULLPTR"
#endif
#if defined(BOOST_NO_CXX11_NUMERIC_LIMITS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_NUMERIC_LIMITS"
#endif
#if defined(BOOST_NO_CXX11_DECLTYPE) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_DECLTYPE"
#endif
#if defined(BOOST_NO_CXX11_HDR_ARRAY) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_HDR_ARRAY"
#endif
#if defined(BOOST_NO_CXX11_ALLOCATOR) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_ALLOCATOR"
#endif
#if defined(BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS"
#endif
#if defined(BOOST_NO_CXX14_AGGREGATE_NSDMI) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_AGGREGATE_NSDMI"
#endif
#if defined(BOOST_NO_CXX14_BINARY_LITERALS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_BINARY_LITERALS"
#endif
#if defined(BOOST_NO_CXX14_CONSTEXPR) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_CONSTEXPR"
#endif
#if defined(BOOST_NO_CXX14_DECLTYPE_AUTO) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_DECLTYPE_AUTO"
#endif
#if defined(BOOST_NO_CXX14_DIGIT_SEPARATORS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_DIGIT_SEPARATORS"
#endif
#if defined(BOOST_NO_CXX14_STD_EXCHANGE) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_STD_EXCHANGE"
#endif
#if defined(BOOST_NO_CXX14_GENERIC_LAMBDAS) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_GENERIC_LAMBDAS"
#endif
#if defined(BOOST_NO_CXX14_HDR_SHARED_MUTEX) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_HDR_SHARED_MUTEX"
#endif
#if defined(BOOST_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES"
#endif
#if defined(BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION"
#endif
#if defined(BOOST_NO_CXX14_VARIABLE_TEMPLATES) && !defined(BOOST_MATH_SHOW_CXX03_WARNING)
#  define BOOST_MATH_SHOW_CXX03_WARNING
#  define BOOST_MATH_CXX03_WARN_REASON "BOOST_NO_CXX14_VARIABLE_TEMPLATES"
#endif

#ifdef BOOST_MATH_SHOW_CXX03_WARNING
//
// The above list includes everything we use, plus a few we're likely to use soon.
// As from March 2020, C++03 support is deprecated, and as from March 2021 will be removed,
// so mark up as such:
//
// March 2021(mborland): C++03 support has been removed. Replace warning with hard error.
//
// Jan 2023(mborland): C++11 support has been removed so tests for C++14 compliance have been added
//
#error Support for C++11 has been removed. The minimum requirement for this library is fully compliant C++14.
#endif

#endif
